[project]
name = "code-diff-doc-gen"
version = "0.1.0"
dependencies = [
    "instructor>=0.5.0",
    "typer>=0.12.1",
    "rich>=13.9.4",
    "libcst>=1.3.0",
    "openai>=1.12.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/code_diff_doc_gen"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]

[project.scripts]
code-diff-doc-gen = "code_diff_doc_gen.cli:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
